name: "Pull Request Labeler"
on:
  pull_request_target:

jobs:
  pr_branch_check:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: Vankka/pr-target-branch-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: /^(?!master$).*/
        exclude: /commaai:.*/
        change-to: ${{ github.base_ref }}
        comment: |
          Your PR should be made against the `master` branch
        already-exists-action: close_this

