name: project metrics run
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
    outputs:
      setup_time:
        value: ${{ jobs.setup.outputs.setup_time }}
      openpilot_size:
        value: ${{ jobs.setup.outputs.openpilot_size }}
      git_size:
        value: ${{ jobs.setup.outputs.git_size }}
      python_venv_size:
        value: ${{ jobs.setup.outputs.python_venv_size }}
      python_packages_count:
        value: ${{ jobs.setup.outputs.python_packages_count }}

concurrency:
  group: project_metrics_run_${{ inputs.platform }}_${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ${{ inputs.platform }}
    outputs:
      setup_time: ${{ steps.setup_time.outputs.setup_time }}
      openpilot_size: ${{ steps.openpilot_size.outputs.openpilot_size }}
      git_size: ${{ steps.git_size.outputs.git_size }}
      python_venv_size: ${{ steps.python_venv_size.outputs.python_venv_size }}
      python_packages_count: ${{ steps.python_packages_count.outputs.python_packages_count }}
    steps:
      - id: setup_time
        name: Setup time
        run: |
          output=$((time curl -fsSL openpilot.comma.ai | bash) 2>&1 | tail -n3 | head -n1 | cut -f2)
          echo "setup_time=$output" >> $GITHUB_OUTPUT
      - id: openpilot_size
        name: openpilot size
        run: |
          output=$(du -hs openpilot --exclude=.git --exclude=.venv | cut -f1)
          echo "openpilot_size=$output" >> $GITHUB_OUTPUT
      - id: git_size
        name: git folder size
        run: |
          output=$(du -hs openpilot/.git | cut -f1)
          echo "git_size=$output" >> $GITHUB_OUTPUT
      - id: python_venv_size
        name: Python venv size
        run: |
          output=$(du -hs openpilot/.venv | cut -f1)
          echo "python_venv_size=$output" >> $GITHUB_OUTPUT
      - name: Activating venv
        run: |
          echo "openpilot/.venv/bin" >> $GITHUB_PATH
      - id: python_packages_count
        name: Python packages count
        run: |
          output=$(uv pip list | tail -n +3 | wc -l)
          echo "python_packages_count=$output" >> $GITHUB_OUTPUT
