name: "ui preview"
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited]
    branches:
      - 'master'
    paths:
      - 'selfdrive/ui/**'
  workflow_dispatch:

env:
  UI_JOB_NAME: "Create UI Report"

jobs:
  preview:
    name: preview
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Getting master ui
        uses: actions/checkout@v4
        with:
          repository: maxime-desroches/ci-artifacts
          ssh-key: ${{ secrets.CI_ARTIFACTS_DEPLOY_KEY }}
          path: ${{ github.workspace }}/master/ci-artifacts
          ref: master_ui

      - name: Getting pr ui
        uses: actions/checkout@v4
        with:
          repository: maxime-desroches/ci-artifacts
          ssh-key: ${{ secrets.CI_ARTIFACTS_DEPLOY_KEY }}
          path: ${{ github.workspace }}/pr/ci-artifacts
          ref: pr_ui

      - name: Finding diff
        run: |
          sudo apt-get install -y imagemagick
          compare -fuzz 2% -highlight-color DeepSkyBlue1 -lowlight-color none ${{ github.workspace }}/master/ci-artifacts/onroad_alert_mid.png ${{ github.workspace }}/pr/ci-artifacts/onroad_alert_mid.png diff.png
          mv diff.png ${{ github.workspace }}/ci-artifacts/pr

      - name: Push Screenshots
        working-directory: ${{ github.workspace }}/ci-artifacts/pr
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add ${{ github.workspace }}/ci-artifacts/pr/diff.png
          git commit -m "screenshots for PR #${{ github.event.number }}"
          git push origin pr_ui --force

      - name: Comment Screenshots on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            <!-- _(run_id_screenshots **${{ github.run_id }}**)_ -->
            ## UI Screenshots
            <table>
              <tr>
                <td><img src="https://raw.githubusercontent.com/maxime-desroches/ci-artifacts/master_ui/onroad_alert_mid.png"></td>
                <td><img src="https://raw.githubusercontent.com/maxime-desroches/ci-artifacts/pr_ui/onroad_alert_mid.png"></td>
              </tr>
              <tr>
                <td><img src="https://raw.githubusercontent.com/maxime-desroches/ci-artifacts/pr_ui/diff.png"></td>
              </tr>
            </table>
          comment_tag: run_id_screenshots
          pr_number: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
