name: "ui preview"
on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'master'
    paths:
      - 'selfdrive/ui/**'

jobs:
  preview:
    name: preview
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Wait for ui report
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Create UI Report'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
          wait-interval: 20

      - name: Get workflow run ID
        id: get_run_id
        run: |
          echo $(curl https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | select(.name == "Create UI Report") | .html_url | capture("(?<number>[0-9]+)") | .number')
          echo $(curl https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | select(.name == "Create UI Report") | .id')
          echo "run_id=$(curl https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | select(.name == "Create UI Report") | .html_url | capture("(?<number>[0-9]+)") | .number')" >> $GITHUB_OUTPUT

      - name: Checkout ci-artifacts
        uses: actions/checkout@v4
        with:
          repository: maxime-desroches/ci-artifacts
          #ssh-key: ${{ secrets.CI_ARTIFACTS_DEPLOY_KEY }}
          path: ${{ github.workspace }}/ci-artifacts
          ref: master
          
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ steps.get_run_id.outputs.run_id }}
          commit: ${{ github.event.pull_request.head.sha }}
          search_artifacts: true
          name: cool-1

      - name: Push Screenshots
        working-directory: ${{ github.workspace }}/ci-artifacts
        run: |
          git checkout -b openpilot/pr-${{ inputs.pr_number }}
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add ${{ github.workspace }}/ci-artifacts/screenshots
          git commit -m "screenshots for PR #${{ github.event.number }}"
          git push origin openpilot/pr-${{ github.event.number }} --force

      - name: Comment Screenshots on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            <!-- _(run_id_screenshots **${{ github.run_id }}**)_ -->
            ## UI Screenshots
            <table>
              <tr>
                <td><img src="https://raw.githubusercontent.com/commaai/ci-artifacts/openpilot/pr-${{ github.event.number }}/report-${{ github.event.number }}/screenshots/homescreen.png"></td>
                <td><img src="https://raw.githubusercontent.com/commaai/ci-artifacts/openpilot/pr-${{ github.event.number }}/report-${{ github.event.number }}/screenshots/onroad.png"></td>
              </tr>
              <tr>
                <td><img src="https://raw.githubusercontent.com/commaai/ci-artifacts/openpilot/pr-${{ github.event.number }}/report-${{ github.event.number }}/screenshots/onroad_map.png"></td>
                <td><img src="https://raw.githubusercontent.com/commaai/ci-artifacts/openpilot/pr-${{ github.event.number }}/report-${{ github.event.number }}/screenshots/onroad_sidebar.png"></td>
              </tr>
              <tr>
                <td><img src="https://raw.githubusercontent.com/commaai/ci-artifacts/openpilot/pr-${{ github.event.number }}/report-${{ github.event.number }}/screenshots/settings_network.png"></td>
                <td><img src="https://raw.githubusercontent.com/commaai/ci-artifacts/openpilot/pr-${{ github.event.number }}/report-${{ github.event.number }}/screenshots/settings_device.png"></td>
              </tr>
            </table>
          pr_number: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
